### ISSUE TITLE
Initial Commit

### ISSUE THREAD

**Issue by sirthxalot** [sirthxalot/vue-foundation-components#1]
## Situation

At this point we will have an empty project ready to get feed with some data. So lets begin and tackle down the default structure of the project.
## Tasks
- [x] **Minor**: Add common project files.
- [x] **Feature**: Define NPM packages and setup development environment.
- [x] **Minor**: Create default structure of the project.
- [x] **Feature**: Create Gulpfile in order to run Gulp tasks.
- [x] **Feature**: Compile and prepare the Foundation assets into the example directory.
- [x] **Feature**: Prepare everything in order to compile the Vue components.
- [x] **Minor**: Add a little dummy component in order to test the component generation.
