### ISSUE TITLE
Available by NPM?

### ISSUE THREAD

**Issue by ktquez** [sirthxalot/vue-foundation-components#13]

**Comment by sirthxalot** [comment]
Hi @ktquez!

Thank you for your request. I will do my best and try it again. Last time I had some issues this is why the package doesn't support npm yet, but I will do my best.

## Tasks

- [x] Update `package.json` for NPM installation;
- [x] Update copyright from 2016 to 2016-2017;
- [x] Update `readme.md` with latest changes.

**Comment by sirthxalot** [comment]
There you go: https://www.npmjs.com/package/vue-foundation-components.
Hope this helps- Thank you for using Vue-Foundation-Components.
